source 'https://rubygems.org'
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end
ruby '>=2.4'
gem 'puma', '~> 5.6.2'
gem 'rails', '~> 6.0.0.0'
gem 'webpacker', '~> 5.0'
# Asset Gems
gem 'angular-rails-templates'
gem 'angularjs-rails', '~> 1.4.7'
gem 'american_date'
gem 'angularjs-rails-resource', '~> 1.0.0'
gem 'autoprefixer-rails'
gem 'bourbon'
gem 'cobravsmongoose'
gem 'coffee-rails'
gem 'combine_pdf'
gem 'font-awesome-sass'
gem 'hiredis'
gem 'webrick', '~> 1.4.4'
